### ISSUE TITLE
[BUG] The UAC authorization window doesn't work properly in some cases

### ISSUE THREAD

**Issue by fallenleave0620** [eythaann/Seelen-UI#112]
**Describe the bug**
The UAC authorization window doesn't work properly in some cases (I tried a quick update of my potplayer and then the UAC authorization window pops up with the corresponding icon in the taskbar, but it doesn't pop up the window to authorize it properly),
but I can't reproduce the bug, I can't just keep updating my apps from the latest version to the latest version.😭💦
**note**
Here's the bug when I was using Beta5

**Comment by fallenleave0620** [comment]
https://github.com/user-attachments/assets/0bbb2c29-84d2-4170-a50b-a28cec4ba493

**Comment by eythaann** [comment]
the uac thing I think is was cuz the seelen-ui app was running without admin rights

**Comment by eythaann** [comment]
the other thing is that sometimes the close event of a window is not triggered so the controls for that window are frozen cuz the app was already closed, but is a little hard to replicate on my machine. btw I know how to add a workaround basically check on action if the window already is valid, otherwise manually trigger the closet window event.

**Comment by eythaann** [comment]
I will solve this issue on #116 so will mark this a duplicated.
