### ISSUE TITLE
[BUG] web app pinning

### ISSUE THREAD

**Issue by GyomeiHimejima9906** [eythaann/Seelen-UI#193]
**Describe the bug**
is imppossible to pin/unpin multiple web app (and the corrisponding brawser) (i think the problem is that web app is managed with same brawer and other web app exetutible file (msedge.exe in this casa)) withou taskmanager and workarounds

**To Reproduce**
1. create 2 web app
2. pin/unpin them
3. you can see that one on them or all are duplicated or similar issues and you see what was made after restarting seelen ui
4. in unpin casa you see that thera are a lor of unpin or incorrecte and you see what was made after restarting seelen ui

**Expected behavior**
can pin web app without a tric and duplications

**videos**
https://github.com/user-attachments/assets/37f9caf7-2bda-40a0-b01b-4f4a96362029
https://github.com/user-attachments/assets/79339edc-77cf-4b70-8d83-ac43b817f1c2

**Comment by eythaann** [comment]
ok this is weird

**Comment by Satyajit-2003** [comment]
I want to pin multiple user profiles of chrome (in the taskbar) and it doesn't let me. I believe it is part of the same problem.

**Comment by luriusTM** [comment]
> I want to pin multiple user profiles of chrome (in the taskbar) and it doesn't let me. I believe it is part of the same problem.

Hi, 

Nope, these two are different. Your problem is about and old feature, which MS put into the StartMenu, which is about relaunch path. This functionality barely used, mostly known by this case. 

(Some notes to developer, because the rootcause analysis was done, but not have yet time to fix... and do not know when will...)

This is the attribute which holds the value: 
<img width="476" alt="image" src="https://github.com/user-attachments/assets/8c01db51-0ae7-478d-8635-f2d28714fad4">

Should be resolved like: 
![image](https://github.com/user-attachments/assets/20db9919-0c77-4a7c-b007-c2fe0748b2c6)
 just with the appropriate getter. Also for the icon handling is with the appropriate value. 

Later on, I will work with this also, but knocked my head with a different issue, around the same territory.

**Comment by luriusTM** [comment]
> **Describe the bug** is imppossible to pin/unpin multiple web app (and the corrisponding brawser) (i think the problem is that web app is managed with same brawer and other web app exetutible file (msedge.exe in this casa)) withou taskmanager and workarounds
> 
> **To Reproduce** Steps to reproduce the behavior:
> 
> 1. create 2 web app
> 2. pin/unpin them
> 3. you can see that one on them or all are duplicated or similar issues and you see what was made after restarting seelen ui
> 4. in unpin casa you see that thera are a lor of unpin or incorrecte and you see what was made after restarting seelen ui
> 
> **Expected behavior** can pin web app without a tric and duplications
> 
> **videos** https://github.com/user-attachments/assets/37f9caf7-2bda-40a0-b01b-4f4a96362029 https://github.com/user-attachments/assets/79339edc-77cf-4b70-8d83-ac43b817f1c2

Hi, 

This is a minor one... will make a PR.
