### ISSUE TITLE
[FEAT] Enable Click / Right-click on items in tray

### ISSUE THREAD

**Issue by jinnius0410** [eythaann/Seelen-UI#229]
At the moment I don't know whether it is a bug with my version or it is not a feature yet but there's no way to click / right-click items in the System Tray. Having the ability to see items in System Tray is great but not having the option access/adjust their options kinda defeated the point. As of right now whenever I need to access the options of those items I need to disable Seleen to get normal taskbar back and then adjust the option in the default System tray.

Suggest Solution: 
Implement the ability to click/right-click items in the System Tray (much like the behavior  of default system tray)

**Comment by eythaann** [comment]
already you can right click on the items

**Comment by jinnius0410** [comment]
Then i guess it must be a bug particular to my setup then ? Is there a way I can send you information or log or anything (Sorry Im not too savy in this area)

**Comment by mrdvojo** [comment]
You can click them but tbh, it is kinda wonky since when you right click for example discord when you want to close it the list will dissapear and you will only see Discords right click menu so its kinda visually wonky plus also idk how it sorts apps but it would be better to have some option as user to either rearange apps or at least set different sorting options.
